replicaCount: 1

image:
  # 'minikube image load' wala exact naam
  repository: watchdog_project_backend-api 
  pullPolicy: Never
  tag: "latest"

serviceAccount:
  create: true
  name: "ai-backend-sa"

service:
  type: ClusterIP
  port: 8000  # Backend Port

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # Rewrite zaroori hai agar backend '/' par listen karta hai aur ingress '/api' redirect karta hai
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ai-project.local
      paths:
        - path: /api
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# AI Models heavy hote hain, isliye probes ko abhi ke liye disabled rakha hai 
# taaki startup ke waqt pod kill na ho jaye
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

httpRoute:
  enabled: false

env:
  - name: ROOT_PATH
    value: "/api"