services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: hrishipatil193/ai-backend:v4
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hrishipatil193/ai-frontend:v1
    ports:
      - "80:80"
    depends_on:
      - backend