replicaCount: 1

image:
  repository: watchdog_project_frontend-ui 
  pullPolicy: Never
  tag: "latest"

service:
  type: ClusterIP
  port: 80         # Bahar se hum 80 pe hi hit karenge
  targetPort: 3000 # Lekin andar Next.js 3000 pe chal raha hai

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ai-project.local
      paths:
        - path: /
          pathType: Prefix

# Resource limits (Next.js aur AI assets ke liye)
resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "500m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false