# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchdog-frontend
  template:
    metadata:
      labels:
        app: watchdog-frontend
    spec:
      containers:
      - name: frontend
        image: hrishipatil193/watchdog-frontend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000  # <--- Dockerfile se match hona chahiye
---
apiVersion: v1
kind: Service
metadata:
  name: watchdog-frontend-svc
spec:
  selector:
    app: watchdog-frontend
  ports:
    - protocol: TCP
      port: 80          # Browser ke liye
      targetPort: 3000  # Container ke andar ka port
  type: ClusterIP